# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-14 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='small_pic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
