# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-31 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20170114_1958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '新闻'},
        ),
        migrations.AddField(
            model_name='admin',
            name='nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='favor_count',
            field=models.IntegerField(default=0, verbose_name='推荐数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NewsType', verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='news',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='news',
            name='small_pic',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(verbose_name='网址'),
        ),
        migrations.AlterField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Admin', verbose_name='添加人'),
        ),
    ]
