# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170131_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnatchUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('url', models.CharField(max_length=255, verbose_name='网址')),
                ('reg', models.CharField(max_length=100, verbose_name='匹配正则')),
                ('num1', models.IntegerField(default=1, verbose_name='一次抓取条数')),
                ('used', models.BooleanField(choices=[(0, '否'), (1, '是')], default=1, verbose_name='启用')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('news_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.NewsType', verbose_name='类型')),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.UserType', verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='news',
            name='snatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.SnatchUrls'),
        ),
    ]
