# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170201_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='snatchurls',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snatchurls',
            name='num2',
            field=models.IntegerField(default=1, verbose_name='每天最多抓取数'),
        ),
        migrations.AlterField(
            model_name='snatchurls',
            name='used',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='启用'),
        ),
    ]
