# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-01 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170201_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='snatchurls',
            name='isdesc',
            field=models.BooleanField(choices=[(1, '降序'), (0, '升序')], default=1, verbose_name='抓取顺序'),
        ),
    ]
