# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_news_hit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isShow',
            field=models.BooleanField(choices=[(1, '是'), (0, '否')], default=1, verbose_name='显示'),
        ),
    ]
