# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_news_isshow'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='isHot',
            field=models.BooleanField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='推荐'),
        ),
    ]
